export const ENDPOINTS = [
  { group: "Auth", items: [
    { method: "mutation" as const, path: "auth.signup", input: "email, password", output: "user, token" },
    { method: "mutation" as const, path: "auth.login", input: "email, password", output: "user, token" },
    { method: "mutation" as const, path: "auth.logout", input: "—", output: "ok" },
    { method: "mutation" as const, path: "auth.changePassword", input: "currentPassword, newPassword", output: "ok" },
    { method: "mutation" as const, path: "auth.setup2FA", input: "—", output: "secret, qrCodeUrl" },
    { method: "mutation" as const, path: "auth.disable2FA", input: "token", output: "ok" },
    { method: "mutation" as const, path: "auth.deleteAccount", input: "—", output: "ok" },
  ]},
  { group: "Trades", items: [
    { method: "query" as const, path: "trades.list", input: "limit (optional)", output: "Trade[]" },
    { method: "query" as const, path: "trades.exportCsv", input: "—", output: "csv string" },
    { method: "mutation" as const, path: "trades.save", input: "symbol, result, stake, entryTime, ...", output: "Trade" },
    { method: "mutation" as const, path: "trades.importCsv", input: "csv string", output: "{ imported: number }" },
  ]},
  { group: "Strategies", items: [
    { method: "query" as const, path: "strategies.list", input: "—", output: "Strategy[]" },
    { method: "mutation" as const, path: "strategies.create", input: "name, config", output: "Strategy" },
    { method: "mutation" as const, path: "strategies.update", input: "id, config", output: "Strategy" },
    { method: "mutation" as const, path: "strategies.duplicate", input: "id", output: "Strategy" },
    { method: "mutation" as const, path: "strategies.delete", input: "id", output: "ok" },
    { method: "mutation" as const, path: "strategies.exportRule", input: "id", output: "json" },
    { method: "mutation" as const, path: "strategies.importRule", input: "json", output: "Strategy" },
    { method: "mutation" as const, path: "strategies.publish", input: "id, published", output: "ok" },
  ]},
  { group: "Bots", items: [
    { method: "query" as const, path: "bot.getRuns", input: "—", output: "BotRun[]" },
    { method: "mutation" as const, path: "bot.startRun", input: "strategyId, safety", output: "BotRun" },
    { method: "mutation" as const, path: "bot.stopRun", input: "id, status", output: "ok" },
    { method: "mutation" as const, path: "bot.stopAll", input: "—", output: "{ stopped: number }" },
    { method: "mutation" as const, path: "bot.saveLog", input: "botRunId, level, message", output: "ok" },
    { method: "query" as const, path: "bot.getLogs", input: "botRunId, limit", output: "BotLog[]" },
  ]},
  { group: "AI / Knowledge", items: [
    { method: "mutation" as const, path: "ai.journal", input: "strategyId, limit", output: "{ analysis }" },
    { method: "query" as const, path: "ai.journalSearch", input: "query, limit", output: "AiKnowledge[]" },
    { method: "mutation" as const, path: "ai.journalSaveManual", input: "note", output: "ok" },
    { method: "mutation" as const, path: "ai.ask", input: "message", output: "{ reply }" },
    { method: "query" as const, path: "aiChat.sendMessage", input: "message", output: "ChatResponse" },
    { method: "query" as const, path: "aiChat.conversationHistory", input: "—", output: "ChatMessage[]" },
    { method: "mutation" as const, path: "aiChat.clearConversation", input: "—", output: "ok" },
    { method: "query" as const, path: "aiChat.memory", input: "type, search, limit", output: "{ entries }" },
    { method: "query" as const, path: "aiChat.modelConfig", input: "—", output: "{ provider, model }" },
    { method: "mutation" as const, path: "aiChat.setModelConfig", input: "provider, model", output: "ok" },
  ]},
  { group: "Alerts & Webhooks", items: [
    { method: "query" as const, path: "alerts.list", input: "—", output: "PriceAlert[]" },
    { method: "mutation" as const, path: "alerts.create", input: "symbol, direction, targetPrice", output: "PriceAlert" },
    { method: "mutation" as const, path: "alerts.disable", input: "id", output: "ok" },
    { method: "query" as const, path: "webhooks.list", input: "—", output: "{ webhooks }" },
    { method: "mutation" as const, path: "webhooks.create", input: "url, events[], label", output: "Webhook" },
    { method: "mutation" as const, path: "webhooks.delete", input: "id", output: "ok" },
  ]},
  { group: "Admin", items: [
    { method: "query" as const, path: "admin.listUsers", input: "—", output: "{ users }" },
    { method: "mutation" as const, path: "admin.promoteToAdmin", input: "userId", output: "ok" },
    { method: "mutation" as const, path: "admin.demoteToUser", input: "userId", output: "ok" },
    { method: "mutation" as const, path: "admin.deleteUser", input: "userId", output: "ok" },
    { method: "query" as const, path: "admin.auditLogs", input: "limit", output: "{ logs }" },
    { method: "query" as const, path: "admin.systemHealth", input: "—", output: "HealthStatus" },
  ]},
  { group: "Market Data", items: [
    { method: "query" as const, path: "market.getHistory", input: "symbol, limit", output: "{ ticks }" },
    { method: "query" as const, path: "market.activeSymbols", input: "—", output: "Symbol[]" },
    { method: "query" as const, path: "market.digitStats", input: "symbol, limit", output: "{ stats }" },
    { method: "query" as const, path: "market.trend", input: "symbol", output: "{ trend }" },
  ]},
  { group: "Coding", items: [
    { method: "query" as const, path: "coding.list", input: "—", output: "{ files }" },
    { method: "query" as const, path: "coding.read", input: "path", output: "{ content }" },
    { method: "mutation" as const, path: "coding.write", input: "path, content", output: "ok" },
    { method: "query" as const, path: "coding.templates", input: "—", output: "{ templates }" },
    { method: "mutation" as const, path: "coding.validate", input: "code", output: "{ valid, errors }" },
    { method: "mutation" as const, path: "coding.saveVersion", input: "path, content", output: "ok" },
    { method: "query" as const, path: "coding.listVersions", input: "path", output: "{ versions }" },
  ]},
  { group: "Signals & Plugins", items: [
    { method: "query" as const, path: "signals.list", input: "—", output: "Signal[]" },
    { method: "query" as const, path: "plugins.marketplace", input: "—", output: "{ plugins }" },
    { method: "query" as const, path: "plugins.my", input: "—", output: "{ plugins }" },
    { method: "mutation" as const, path: "plugins.install", input: "pluginId, enabled", output: "ok" },
  ]},
  { group: "Other", items: [
    { method: "query" as const, path: "globalSearch", input: "query", output: "{ trades, strategies, botRuns, aiKnowledge }" },
    { method: "query" as const, path: "memory.get", input: "—", output: "{ memory }" },
    { method: "mutation" as const, path: "memory.set", input: "memory", output: "ok" },
    { method: "query" as const, path: "settings.notifications", input: "—", output: "{ settings }" },
    { method: "mutation" as const, path: "settings.notifications", input: "settings", output: "ok" },
    { method: "query" as const, path: "aiPerformance.overview", input: "—", output: "PerformanceOverview" },
    { method: "query" as const, path: "aiPerformance.accuracyDetail", input: "—", output: "AccuracyDetail" },
  ]},
];
